// examples/vue/src/components/badge.island.tsx
import { defineComponent, onMounted, ref } from 'vue';
import { withHydration } from '@comity/vue';
import { filename } from 'virtual:comity-islands';
import Template from './badge.vue';

export const Badge = defineComponent({
  name: 'Badge',
  props: {
    server: String,
    client: String,
  },
  setup(props) {
    const env = ref(props.server || 'server');

    onMounted(() => {
      if (typeof window !== 'undefined') {
        env.value = props.client || 'client';
      }
    });

    return { env };
  },
  render() {
    return <Template env={this.env} />;
  },
});

export const BadgeIsland = withHydration(Badge, filename);

export default BadgeIsland;

// templates/preact/src/components/badge.island.tsx
import type { FunctionComponent as FC } from 'preact';
import { useEffect, useState } from 'preact/hooks';
import { withHydration } from '@comity/preact';
import { filename } from 'virtual:comity-islands';

type Props = {
  server?: string;
  client?: string;
};

// testing island inside island
export const Badge: FC<Props> = ({ client, server }) => {
  const [env, setEnv] = useState<string>(server || 'server');

  useEffect(() => {
    if (typeof window !== 'undefined') setEnv(client || 'client');
  });

  return <span>Hey {env}!</span>;
};

export const BadgeIsland = withHydration(Badge, filename);

export default BadgeIsland;
